eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url: #eureka server 注册中心的地址，用于client和server交流
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/

server:
  port: 8766
spring:
  application:
    name: eureka-client-service-provider

